# Generated by Django 4.2 on 2023-04-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='app.department_db'),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='manager_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='app.manager_db'),
        ),
    ]
